
namespace Node 
{
    public class MetaNode : INode 
    { 
        // IMPORTANT THAT THIS IS GENERATED BY NODE ITSELF
        public string ID {get; set;} = Params.UNIQUE_KEY;

        // Can be adjusted
        public string Host {get; set;} = Params.ADVERTISED_HOST_NAME;
        public int Port {get; set;} = Params.PORT_NUMBER;
        public string Name {get; set;} = Params.NODE_NAME;

        // The jobs that THIS node have
        public Job[] Jobs {get; set;} = Scheduler.Instance._Jobs;

        // The other nodes which THIS node knows about
        public BasicNode[] Nodes {get; set;} = Ledger.Instance.Cluster.AsNodeArray().AsBasicNodes().ToArray(); 
    }
}