
namespace Node
{
    class PlainMetaNode 
    {
        // IMPORTANT THAT THIS IS GENERATED BY NODE ITSELF
        public string ID {get; set;} = Params.UNIQUE_KEY;

        // Can be adjusted
        public string Host {get; set;} = Params.ADVERTISED_HOST_NAME;
        public int Port {get; set;} = Params.PORT_NUMBER;
        public string Name {get; set;} = Params.NODE_NAME;

        public static MetaNode MakeMetaNode(PlainMetaNode node )
        {
            return new MetaNode(){
                ID = node.ID,
                Host = node.Host,
                Port = node.Port,
                Name = node.Name,
                Jobs = new Job[]{},
                Nodes = new BasicNode[]{}
            };
        }

        public static PlainMetaNode MakePlainMetaNode(MetaNode node)
        {
            return new PlainMetaNode(){
                ID = node.ID,
                Host = node.Host,
                Port = node.Port,
                Name = node.Name
            };
        }
    }
}